# Generated by Django 3.0.5 on 2020-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KioskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacja', models.CharField(choices=[('W', 'Wybierz'), ('P', 'Przywieź'), ('Z', 'Zawieź')], max_length=120)),
                ('numer_zam', models.IntegerField(error_messages={'invalid': 'Podaj wartość liczbową'})),
                ('id_materialu', models.IntegerField(error_messages={'invalid': 'Podaj wartość liczbową'})),
                ('material', models.CharField(choices=[('W', 'Wybierz'), ('S', 'Śrubka'), ('G', 'Gwoździe')], max_length=120)),
                ('ilosc', models.IntegerField(error_messages={'invalid': 'Podaj wartość liczbową'})),
                ('cel', models.CharField(choices=[('W', 'Wybierz'), ('1', 'Strefa wydań'), ('2', 'Strefa kompletacji'), ('3', 'Magazyn')], max_length=120)),
                ('opis', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='KioskSelectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk', models.CharField(choices=[('1', 'Kiosk1'), ('2', 'Kiosk2'), ('3', 'Kiosk3')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TargetPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.CharField(choices=[('1', 'Strefa wydań'), ('2', 'Strefa kompletacji'), ('3', 'Magazyn')], max_length=120)),
            ],
        ),
    ]
