# Generated by Django 3.0.5 on 2020-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskselectmodel',
            name='kiosk',
            field=models.CharField(max_length=120),
        ),
    ]
