# Generated by Django 3.0.5 on 2020-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20200508_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KioskSelectModel',
        ),
        migrations.RenameField(
            model_name='kioskmodel',
            old_name='opis',
            new_name='kiosk',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='id_materialu',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='ilosc',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='material',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='numer_zam',
        ),
        migrations.RemoveField(
            model_name='kioskmodel',
            name='operacja',
        ),
    ]
