# Generated by Django 3.0.5 on 2020-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20200508_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskmodel',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kioskmodel',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kioskmodel',
            name='z',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
