# Generated by Django 3.0.5 on 2020-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20200508_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('password_api', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TargetParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.CharField(choices=[('1', 'parking-01'), ('2', 'parking-02'), ('3', 'parking-03'), ('4', 'Charger')], max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='kioskmodel',
            name='x',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='kioskmodel',
            name='y',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='kioskmodel',
            name='z',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='targetposition',
            name='pozycja',
            field=models.CharField(choices=[('1', 'prawy dolny rog 5e4602ba9184b62beee348c9'), ('2', 'A 5e4691cf59f001700ceaf72a'), ('3', 'C 5e4691da59f001700ceaf72c')], max_length=120),
        ),
    ]
